# -*- coding: utf-8 -*-
"""password generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UjVh7hR4bU9e0eqy0bJ_JECnIqvO6U2r
"""

import random
import string

def generate_password(length, complexity):
    if complexity == 'low':
        characters = string.ascii_letters
    elif complexity == 'medium':
        characters = string.ascii_letters + string.digits
    elif complexity == 'high':
        characters = string.ascii_letters + string.digits + string.punctuation
    else:
        raise ValueError("Invalid complexity level. Choose 'Low', 'Medium', or 'High'.")

    password = ''.join(random.choice(characters) for i in range(length))
    return password

def main():
    length = int(input("Enter the length of the password: "))
    complexity = input("Enter the complexity (Low, Medium, High): ").lower()

    try:
        password = generate_password(length, complexity)
        print(f"Generated Password: {password}")
    except ValueError as e:
        print(e)

if __name__ == "__main__":
    main()